// Barrel for Epic 0 shared components — screens import from '../components'.

export { PageHeader } from './PageHeader'
export { Card, Panel, StatGrid } from './Card'
export { DataTable, Pagination } from './DataTable'
export type { Column, DataTableProps, PaginationProps } from './DataTable'
export { Modal, Drawer, ConfirmDialog } from './Modal'
export type { ModalProps, DrawerProps, ConfirmDialogProps } from './Modal'
export { Field, Input, Textarea, Select, Toggle } from './Form'
export type { FieldProps, InputProps, TextareaProps, SelectProps, SelectOption, ToggleProps } from './Form'
export { FileUpload } from './FileUpload'
export type { FileUploadProps } from './FileUpload'
export { StatCard, StatusPill, Badge, FilterBar, EmptyState, Toast } from './ui'
// New design-system primitives (clean-light redesign Task N3)
export { Avatar, avColor, AV_COLORS } from './Avatar'
export type { AvatarProps } from './Avatar'
export { CHANNELS, channelOf } from './channels'
export type { ChannelDef } from './channels'
export { ChanGlyph } from './ChanGlyph'
export type { ChanGlyphProps } from './ChanGlyph'
export { Chip, Tag, TAG_COLORS } from './Chip'
export type { ChipProps, TagProps } from './Chip'
export { KpiCard } from './KpiCard'
export type { KpiCardProps } from './KpiCard'
export { Bar } from './Bar'
export type { BarProps } from './Bar'
